name: Build and Test

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release
    
    - name: Run tests
      run: dotnet test --no-build --verbosity normal